//
//  DetailPokemonViewController.swift
//  PokedexNew
//
//  Created Administrator on 13/06/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailPokemonViewController: UIViewController {

    //MARK: - Protocol Properties
	var presenter: DetailPokemonPresenterProtocol?

    //MARK: - Properties
    var detallesPokemon: Pokemon?
//    var pokemons: favorite?
    private var imagenPokemon: UIImageView = {
        let imageView = UIImageView()
//        imageView.image = UIImage(named: "pokemon")
        imageView.translatesAutoresizingMaskIntoConstraints = false
        return imageView
    }()
    private var labelDescription: UILabel = {
        let label = UILabel()
        label.text = "Bulbasaur es un Pokémon cuadrúpedo de color verde, posee manchas de una tonalidad más oscura del mismo color con distintas formas geométricas. Su cabeza representa cerca de un tercio de su cuerpo. En su frente se ubican tres manchas que pueden cambiar de posición, forma o lugar dependiendo del ejemplar. Tiene como orejas muñones pequeños y puntiagudos. Sus ojos son grandes y de color rojo. Sus patas son cortas y posee tres garras en cada una. Este Pokémon tiene plantado un bulbo en el lomo desde que nace, esta semilla crece y se desarrolla a lo largo del ciclo de vida de Bulbasaur a medida que suceden sus evoluciones. El bulbo absorbe y almacena la energía solar que Bulbasaur necesita para hacer florecer el bulbo de su lomo y evolucionar en Ivysaur."
        label.numberOfLines = 50
        label.translatesAutoresizingMaskIntoConstraints = false
        return label
    }()
    
    private var labelName: UILabel = {
        let label = UILabel()
        label.text = "Bulbasor"
        if #available(iOS 16.0, *) {
            label.font = .systemFont(ofSize: 25, weight: .black, width: .condensed)
        } else {
            // Fallback on earlier versions
        }
        label.translatesAutoresizingMaskIntoConstraints = false
        return label
    }()
    
    private var labelNumberDefensa: UILabel = {
        let label = UILabel()
        label.text = "Defensa: 49"
        return label
    }()
    
    private var labelNumberAtaque: UILabel = {
        let label = UILabel()
        label.text = "Ataque: 45"
        label.translatesAutoresizingMaskIntoConstraints = false
        return label
    }()
    
    
    //MARK: - Life Cycle
	override func viewDidLoad() {
        view.backgroundColor = .white
        super.viewDidLoad()
        setupUi()
    }
    
    //MARK: - Methods
    func setupUi(){
        var buttonFav = UIBarButtonItem(image: UIImage(systemName: "suit.heart"), style: .done, target: self, action: #selector(favorite))
        navigationItem.rightBarButtonItem = buttonFav
        
        view.addSubview(imagenPokemon)
        view.addSubview(labelDescription)
        view.addSubview(labelName)
        view.addSubview(labelNumberAtaque)
        view.addSubview(labelNumberDefensa)
        
        labelName.addAnchorsAndCenter(centerX: true, centerY: nil, width: nil, height: nil, left: nil, top: 85, right: nil, bottom: nil)
        imagenPokemon.addAnchorsAndCenter(centerX: true, centerY: false, width: 250, height: 250, left: nil, top: 10, right: nil, bottom: nil, withAnchor: .top, relativeToView: labelName)
        labelDescription.addAnchorsAndSize(width: nil, height: nil, left: 20, top: 10, right: 20, bottom: nil, withAnchor: .top, relativeToView: labelNumberAtaque)
        labelNumberAtaque.addAnchorsAndSize(width: nil, height: nil, left: 20, top: 20, right: nil, bottom: nil, withAnchor: .top, relativeToView: imagenPokemon)
        labelNumberDefensa.addAnchorsAndSize(width: nil, height: nil, left: nil, top: 20, right: 20, bottom: nil, withAnchor: .top, relativeToView: imagenPokemon)
        
        labelName.text = detallesPokemon?.name
        labelDescription.text = detallesPokemon?.description
        guard let ataque = detallesPokemon?.attack else { return }
        labelNumberAtaque.text = "Ataque: \(ataque)"
        guard let defensa = detallesPokemon?.defense else { return }
        labelNumberDefensa.text = "Defensa: \(defensa)"
       
        if let urlString = detallesPokemon?.imageUrl as? String {
            if let imagenURL = URL(string: urlString) {
                DispatchQueue.global().async {
                    guard let imagenData = try? Data(contentsOf: imagenURL) else{
                        return }
                    let image = UIImage(data: imagenData)
                    DispatchQueue.main.async {
                        self.imagenPokemon.image = image
                    }
                }
            }
        }
    }
}

//MARK: - View Methods
extension DetailPokemonViewController: DetailPokemonViewProtocol {
    func detailPokemon(pokemonSeleccionado: Pokemon) {
        print("detalles del poemon ya estan en el nuevo viewController:::: \(pokemonSeleccionado)")
        detallesPokemon = pokemonSeleccionado
    }
    
    
}

//MARK: - Private functions
extension DetailPokemonViewController {
    @objc func favorite(){
//        
//        newPokemon?.name = labelName
//        newPokemon?.defense = labelNumberDefensa
//        newPokemon?.attack = labelNumberAtaque
//    
        print(labelName)
        print(labelDescription)
        print(labelNumberAtaque)
        print(labelNumberDefensa)
        
        
        
    }
    
}
