//
//  DetailPokemonInteractor.swift
//  PokedexNew
//
//  Created Administrator on 13/06/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailPokemonInteractor {
    //MARK: - Protocol Properties
    weak var presenter: DetailPokemonPresenterProtocol?
}

//MARK: - Interactor Methods
extension DetailPokemonInteractor: DetailPokemonInteractorProtocol {
    
}
