//
//  DetailPokemonRouter.swift
//  PokedexNew
//
//  Created Administrator on 13/06/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailPokemonRouter {
    //MARK: - Protocol Properties
    weak var viewController: UIViewController?
    
    //MARK: - Static Methods
    static func createModule(pokemonSeleccionado: Pokemon) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = DetailPokemonViewController(nibName: nil, bundle: nil)
        let interactor = DetailPokemonInteractor()
        let router = DetailPokemonRouter()
        let presenter = DetailPokemonPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        print("los datos del pokemon ya estan en el nuevo router::: \(pokemonSeleccionado)")
        presenter.detailPokemon(pokemonSeleccionado: pokemonSeleccionado)
        
        return view
    }
}

//MARK: - Router Metods
extension DetailPokemonRouter: DetailPokemonWireframeProtocol {
    
}

//MARK: - Private functions
extension DetailPokemonRouter {
    
}
