//
//  HomePokedexRouter.swift
//  PokedexNew
//
//  Created Administrator on 10/06/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomePokedexRouter {
    //MARK: - Protocol Properties
    weak var viewController: UIViewController?
    
    //MARK: - Static Methods
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = HomePokedexViewController(nibName: nil, bundle: nil)
        let interactor = HomePokedexInteractor()
        let router = HomePokedexRouter()
        let presenter = HomePokedexPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}

//MARK: - Router Metods
extension HomePokedexRouter: HomePokedexWireframeProtocol {
    func pokemonSeleccionado(pokemonSeleccionado: Pokemon) {
        print("los detalles del pokemon ya estan en el router:::::: \(pokemonSeleccionado)")
        let vc = DetailPokemonRouter.createModule(pokemonSeleccionado: pokemonSeleccionado)
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
    
    
}

//MARK: - Private functions
extension HomePokedexRouter {
    
}
