//
//  HomePokedexProtocols.swift
//  PokedexNew
//
//  Created Administrator on 10/06/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HomePokedexWireframeProtocol: AnyObject {
    func pokemonSeleccionado(pokemonSeleccionado: Pokemon)
}
//MARK: Presenter -
protocol HomePokedexPresenterProtocol: AnyObject {
    func info(datos: [Pokemon])
    func getInitData()
    func pokemonSeleccionado(pokemonSeleccionado: Pokemon)
}

//MARK: Interactor -
protocol HomePokedexInteractorProtocol: AnyObject {

  var presenter: HomePokedexPresenterProtocol?  { get set }
    func getInitData()
}

//MARK: View -
protocol HomePokedexViewProtocol: AnyObject {
    func info(datos: [Pokemon])
    
  var presenter: HomePokedexPresenterProtocol?  { get set }
}
