//
//  HomePokedexPresenter.swift
//  PokedexNew
//
//  Created Administrator on 10/06/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomePokedexPresenter {
    //MARK: - Protocol Properties
    weak private var view: HomePokedexViewProtocol?
    var interactor: HomePokedexInteractorProtocol?
    private let router: HomePokedexWireframeProtocol

    //MARK: - Life Cycle
    init(interface: HomePokedexViewProtocol, interactor: HomePokedexInteractorProtocol?, router: HomePokedexWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

//MARK: - Presenter Methods
extension HomePokedexPresenter: HomePokedexPresenterProtocol {
    func pokemonSeleccionado(pokemonSeleccionado: Pokemon) {
        router.pokemonSeleccionado(pokemonSeleccionado: pokemonSeleccionado)
    }
    
    func getInitData() {
        interactor?.getInitData()
    }
    
    func info(datos: [Pokemon]) {
        view?.info(datos: datos)
        print("los datos ya estan en el presenter:::: \(datos)")
    }
    
    
}

//MARK: - Private functions
extension HomePokedexPresenter {
    
}
